// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Data.AppDbContext;

#nullable disable

namespace University.Data.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260310040407_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ismaeel.moussa1@gmail.com",
                            Name = "Ismaeel-Moussa"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatehabdalsalam@gmail.com",
                            Name = "Abdulsalam-Fateh"
                        },
                        new
                        {
                            Id = 3,
                            Email = "aeter520@gmail.com",
                            Name = "Ahmad-Thaer-Ater"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ihababuwardah@gmail.com",
                            Name = "Ihap-Abuwarda"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mohamadrimi12345@gmail.com",
                            Name = "Muhammed-Elrimi"
                        },
                        new
                        {
                            Id = 6,
                            Email = "wasemalhariri13@gmail.com",
                            Name = "Wasem-Alhariri"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
